// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_ping.proto

package com.tencent.attribution.flink.proto.gdt;

public final class GDTHttpPingService {
    private GDTHttpPingService() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public enum HttpPingDataType
            implements com.google.protobuf.ProtocolMessageEnum {
        UNKNOWN(0, 0),
        GDT_EXPOSURE_THIRDPARTY_MONITOR(1, 1),
        GDT_EXPOSURE_DSP_MONITOR(2, 2),
        WECHAT_EXPOSURE_THIRDPARTY_MONITOR(3, 3),
        WECHAT_EXPOSURE_DSP_MONITOR(4, 4),
        CLICK_MONITOR_FOR_MOBILEAPP_ACTIVITION(5, 5),
        CLICK_DSP_MONITOR(6, 6),
        CLICK_THIRDPARTY_MONITOR(7, 7),
        EXPOSURE_THIRDPARTY_MONITOR_FOR_ADX(8, 8),
        CLICK_DISPATCH_REDO(9, 9),
        CLICK_LANDING_PAGE(10, 10),
        CLICK_TRACKING_JD(11, 11),
        CLICK_TRACKING_58(12, 12),
        CLICK_DSP_FOR_TRACE_COLLECTION(13, 13),
        TRACE_DSP_MONITOR(14, 14),
        DISPATCH_FOR_ADPLATFORM(15, 15),
        DISPATCH_FOR_DSP(16, 16),
        CLICK_FOR_THIRDPARTY_MONITOR(17, 257),
        CLICK_FOR_MOBILEAPP_ACTIVITION(18, 258),
        EXPOSURE_FOR_WECHAT_THIRDPARTY_MONITOR(19, 513),
        WECHAT_TRACE_DISPATCH(20, 514),
        ;

        public static final int UNKNOWN_VALUE = 0;
        public static final int GDT_EXPOSURE_THIRDPARTY_MONITOR_VALUE = 1;
        public static final int GDT_EXPOSURE_DSP_MONITOR_VALUE = 2;
        public static final int WECHAT_EXPOSURE_THIRDPARTY_MONITOR_VALUE = 3;
        public static final int WECHAT_EXPOSURE_DSP_MONITOR_VALUE = 4;
        public static final int CLICK_MONITOR_FOR_MOBILEAPP_ACTIVITION_VALUE = 5;
        public static final int CLICK_DSP_MONITOR_VALUE = 6;
        public static final int CLICK_THIRDPARTY_MONITOR_VALUE = 7;
        public static final int EXPOSURE_THIRDPARTY_MONITOR_FOR_ADX_VALUE = 8;
        public static final int CLICK_DISPATCH_REDO_VALUE = 9;
        public static final int CLICK_LANDING_PAGE_VALUE = 10;
        public static final int CLICK_TRACKING_JD_VALUE = 11;
        public static final int CLICK_TRACKING_58_VALUE = 12;
        public static final int CLICK_DSP_FOR_TRACE_COLLECTION_VALUE = 13;
        public static final int TRACE_DSP_MONITOR_VALUE = 14;
        public static final int DISPATCH_FOR_ADPLATFORM_VALUE = 15;
        public static final int DISPATCH_FOR_DSP_VALUE = 16;
        public static final int CLICK_FOR_THIRDPARTY_MONITOR_VALUE = 257;
        public static final int CLICK_FOR_MOBILEAPP_ACTIVITION_VALUE = 258;
        public static final int EXPOSURE_FOR_WECHAT_THIRDPARTY_MONITOR_VALUE = 513;
        public static final int WECHAT_TRACE_DISPATCH_VALUE = 514;


        public final int getNumber() { return value; }

        public static HttpPingDataType valueOf(int value) {
            switch (value) {
                case 0: return UNKNOWN;
                case 1: return GDT_EXPOSURE_THIRDPARTY_MONITOR;
                case 2: return GDT_EXPOSURE_DSP_MONITOR;
                case 3: return WECHAT_EXPOSURE_THIRDPARTY_MONITOR;
                case 4: return WECHAT_EXPOSURE_DSP_MONITOR;
                case 5: return CLICK_MONITOR_FOR_MOBILEAPP_ACTIVITION;
                case 6: return CLICK_DSP_MONITOR;
                case 7: return CLICK_THIRDPARTY_MONITOR;
                case 8: return EXPOSURE_THIRDPARTY_MONITOR_FOR_ADX;
                case 9: return CLICK_DISPATCH_REDO;
                case 10: return CLICK_LANDING_PAGE;
                case 11: return CLICK_TRACKING_JD;
                case 12: return CLICK_TRACKING_58;
                case 13: return CLICK_DSP_FOR_TRACE_COLLECTION;
                case 14: return TRACE_DSP_MONITOR;
                case 15: return DISPATCH_FOR_ADPLATFORM;
                case 16: return DISPATCH_FOR_DSP;
                case 257: return CLICK_FOR_THIRDPARTY_MONITOR;
                case 258: return CLICK_FOR_MOBILEAPP_ACTIVITION;
                case 513: return EXPOSURE_FOR_WECHAT_THIRDPARTY_MONITOR;
                case 514: return WECHAT_TRACE_DISPATCH;
                default: return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<HttpPingDataType>
        internalGetValueMap() {
            return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<HttpPingDataType>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<HttpPingDataType>() {
                    public HttpPingDataType findValueByNumber(int number) {
                        return HttpPingDataType.valueOf(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.getDescriptor().getEnumTypes().get(0);
        }

        private static final HttpPingDataType[] VALUES = {
                UNKNOWN, GDT_EXPOSURE_THIRDPARTY_MONITOR, GDT_EXPOSURE_DSP_MONITOR, WECHAT_EXPOSURE_THIRDPARTY_MONITOR, WECHAT_EXPOSURE_DSP_MONITOR, CLICK_MONITOR_FOR_MOBILEAPP_ACTIVITION, CLICK_DSP_MONITOR, CLICK_THIRDPARTY_MONITOR, EXPOSURE_THIRDPARTY_MONITOR_FOR_ADX, CLICK_DISPATCH_REDO, CLICK_LANDING_PAGE, CLICK_TRACKING_JD, CLICK_TRACKING_58, CLICK_DSP_FOR_TRACE_COLLECTION, TRACE_DSP_MONITOR, DISPATCH_FOR_ADPLATFORM, DISPATCH_FOR_DSP, CLICK_FOR_THIRDPARTY_MONITOR, CLICK_FOR_MOBILEAPP_ACTIVITION, EXPOSURE_FOR_WECHAT_THIRDPARTY_MONITOR, WECHAT_TRACE_DISPATCH,
        };

        public static HttpPingDataType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private HttpPingDataType(int index, int value) {
            this.index = index;
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.tencent.attribution.flink.proto.gdt.HttpPingDataType)
    }

    public interface HttpPingRecordOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional uint32 process_time = 1;
        boolean hasProcessTime();
        int getProcessTime();

        // optional uint32 partition_time = 2;
        boolean hasPartitionTime();
        int getPartitionTime();

        // optional .com.tencent.attribution.flink.proto.gdt.HttpPingDataType data_type = 3;
        boolean hasDataType();
        com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType getDataType();

        // optional string url = 4;
        boolean hasUrl();
        String getUrl();

        // optional uint32 error_code = 5;
        boolean hasErrorCode();
        int getErrorCode();

        // optional uint32 http_status = 6;
        boolean hasHttpStatus();
        int getHttpStatus();

        // optional string caller_ip = 7;
        boolean hasCallerIp();
        String getCallerIp();

        // optional string local_ip = 8;
        boolean hasLocalIp();
        String getLocalIp();

        // optional string string1 = 9;
        boolean hasString1();
        String getString1();

        // optional string string2 = 10;
        boolean hasString2();
        String getString2();

        // optional string string3 = 11;
        boolean hasString3();
        String getString3();

        // optional string string4 = 12;
        boolean hasString4();
        String getString4();

        // optional string string5 = 13;
        boolean hasString5();
        String getString5();

        // optional bool is_redirected_url = 14;
        boolean hasIsRedirectedUrl();
        boolean getIsRedirectedUrl();
    }
    public static final class HttpPingRecord extends
            com.google.protobuf.GeneratedMessage
            implements HttpPingRecordOrBuilder {
        // Use HttpPingRecord.newBuilder() to construct.
        private HttpPingRecord(Builder builder) {
            super(builder);
        }
        private HttpPingRecord(boolean noInit) {}

        private static final HttpPingRecord defaultInstance;
        public static HttpPingRecord getDefaultInstance() {
            return defaultInstance;
        }

        public HttpPingRecord getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_fieldAccessorTable;
        }

        private int bitField0_;
        // optional uint32 process_time = 1;
        public static final int PROCESS_TIME_FIELD_NUMBER = 1;
        private int processTime_;
        public boolean hasProcessTime() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getProcessTime() {
            return processTime_;
        }

        // optional uint32 partition_time = 2;
        public static final int PARTITION_TIME_FIELD_NUMBER = 2;
        private int partitionTime_;
        public boolean hasPartitionTime() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getPartitionTime() {
            return partitionTime_;
        }

        // optional .com.tencent.attribution.flink.proto.gdt.HttpPingDataType data_type = 3;
        public static final int DATA_TYPE_FIELD_NUMBER = 3;
        private com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType dataType_;
        public boolean hasDataType() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType getDataType() {
            return dataType_;
        }

        // optional string url = 4;
        public static final int URL_FIELD_NUMBER = 4;
        private java.lang.Object url_;
        public boolean hasUrl() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public String getUrl() {
            java.lang.Object ref = url_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    url_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional uint32 error_code = 5;
        public static final int ERROR_CODE_FIELD_NUMBER = 5;
        private int errorCode_;
        public boolean hasErrorCode() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        public int getErrorCode() {
            return errorCode_;
        }

        // optional uint32 http_status = 6;
        public static final int HTTP_STATUS_FIELD_NUMBER = 6;
        private int httpStatus_;
        public boolean hasHttpStatus() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        public int getHttpStatus() {
            return httpStatus_;
        }

        // optional string caller_ip = 7;
        public static final int CALLER_IP_FIELD_NUMBER = 7;
        private java.lang.Object callerIp_;
        public boolean hasCallerIp() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        public String getCallerIp() {
            java.lang.Object ref = callerIp_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    callerIp_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getCallerIpBytes() {
            java.lang.Object ref = callerIp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                callerIp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string local_ip = 8;
        public static final int LOCAL_IP_FIELD_NUMBER = 8;
        private java.lang.Object localIp_;
        public boolean hasLocalIp() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        public String getLocalIp() {
            java.lang.Object ref = localIp_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    localIp_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getLocalIpBytes() {
            java.lang.Object ref = localIp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                localIp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string string1 = 9;
        public static final int STRING1_FIELD_NUMBER = 9;
        private java.lang.Object string1_;
        public boolean hasString1() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        public String getString1() {
            java.lang.Object ref = string1_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    string1_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getString1Bytes() {
            java.lang.Object ref = string1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                string1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string string2 = 10;
        public static final int STRING2_FIELD_NUMBER = 10;
        private java.lang.Object string2_;
        public boolean hasString2() {
            return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        public String getString2() {
            java.lang.Object ref = string2_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    string2_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getString2Bytes() {
            java.lang.Object ref = string2_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                string2_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string string3 = 11;
        public static final int STRING3_FIELD_NUMBER = 11;
        private java.lang.Object string3_;
        public boolean hasString3() {
            return ((bitField0_ & 0x00000400) == 0x00000400);
        }
        public String getString3() {
            java.lang.Object ref = string3_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    string3_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getString3Bytes() {
            java.lang.Object ref = string3_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                string3_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string string4 = 12;
        public static final int STRING4_FIELD_NUMBER = 12;
        private java.lang.Object string4_;
        public boolean hasString4() {
            return ((bitField0_ & 0x00000800) == 0x00000800);
        }
        public String getString4() {
            java.lang.Object ref = string4_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    string4_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getString4Bytes() {
            java.lang.Object ref = string4_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                string4_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string string5 = 13;
        public static final int STRING5_FIELD_NUMBER = 13;
        private java.lang.Object string5_;
        public boolean hasString5() {
            return ((bitField0_ & 0x00001000) == 0x00001000);
        }
        public String getString5() {
            java.lang.Object ref = string5_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    string5_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getString5Bytes() {
            java.lang.Object ref = string5_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                string5_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional bool is_redirected_url = 14;
        public static final int IS_REDIRECTED_URL_FIELD_NUMBER = 14;
        private boolean isRedirectedUrl_;
        public boolean hasIsRedirectedUrl() {
            return ((bitField0_ & 0x00002000) == 0x00002000);
        }
        public boolean getIsRedirectedUrl() {
            return isRedirectedUrl_;
        }

        private void initFields() {
            processTime_ = 0;
            partitionTime_ = 0;
            dataType_ = com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType.UNKNOWN;
            url_ = "";
            errorCode_ = 0;
            httpStatus_ = 0;
            callerIp_ = "";
            localIp_ = "";
            string1_ = "";
            string2_ = "";
            string3_ = "";
            string4_ = "";
            string5_ = "";
            isRedirectedUrl_ = false;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, processTime_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeUInt32(2, partitionTime_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeEnum(3, dataType_.getNumber());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getUrlBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeUInt32(5, errorCode_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeUInt32(6, httpStatus_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBytes(7, getCallerIpBytes());
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeBytes(8, getLocalIpBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                output.writeBytes(9, getString1Bytes());
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                output.writeBytes(10, getString2Bytes());
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                output.writeBytes(11, getString3Bytes());
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                output.writeBytes(12, getString4Bytes());
            }
            if (((bitField0_ & 0x00001000) == 0x00001000)) {
                output.writeBytes(13, getString5Bytes());
            }
            if (((bitField0_ & 0x00002000) == 0x00002000)) {
                output.writeBool(14, isRedirectedUrl_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, processTime_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, partitionTime_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, dataType_.getNumber());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getUrlBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, errorCode_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, httpStatus_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(7, getCallerIpBytes());
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(8, getLocalIpBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(9, getString1Bytes());
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(10, getString2Bytes());
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(11, getString3Bytes());
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(12, getString4Bytes());
            }
            if (((bitField0_ & 0x00001000) == 0x00001000)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(13, getString5Bytes());
            }
            if (((bitField0_ & 0x00002000) == 0x00002000)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(14, isRedirectedUrl_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecordOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_fieldAccessorTable;
            }

            // Construct using com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                processTime_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                partitionTime_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                dataType_ = com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType.UNKNOWN;
                bitField0_ = (bitField0_ & ~0x00000004);
                url_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                errorCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                httpStatus_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                callerIp_ = "";
                bitField0_ = (bitField0_ & ~0x00000040);
                localIp_ = "";
                bitField0_ = (bitField0_ & ~0x00000080);
                string1_ = "";
                bitField0_ = (bitField0_ & ~0x00000100);
                string2_ = "";
                bitField0_ = (bitField0_ & ~0x00000200);
                string3_ = "";
                bitField0_ = (bitField0_ & ~0x00000400);
                string4_ = "";
                bitField0_ = (bitField0_ & ~0x00000800);
                string5_ = "";
                bitField0_ = (bitField0_ & ~0x00001000);
                isRedirectedUrl_ = false;
                bitField0_ = (bitField0_ & ~0x00002000);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord.getDescriptor();
            }

            public com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord getDefaultInstanceForType() {
                return com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord.getDefaultInstance();
            }

            public com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord build() {
                com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord buildPartial() {
                com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord result = new com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.processTime_ = processTime_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.partitionTime_ = partitionTime_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.dataType_ = dataType_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.url_ = url_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.errorCode_ = errorCode_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.httpStatus_ = httpStatus_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.callerIp_ = callerIp_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.localIp_ = localIp_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.string1_ = string1_;
                if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
                    to_bitField0_ |= 0x00000200;
                }
                result.string2_ = string2_;
                if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
                    to_bitField0_ |= 0x00000400;
                }
                result.string3_ = string3_;
                if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
                    to_bitField0_ |= 0x00000800;
                }
                result.string4_ = string4_;
                if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
                    to_bitField0_ |= 0x00001000;
                }
                result.string5_ = string5_;
                if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
                    to_bitField0_ |= 0x00002000;
                }
                result.isRedirectedUrl_ = isRedirectedUrl_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord) {
                    return mergeFrom((com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord other) {
                if (other == com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord.getDefaultInstance()) return this;
                if (other.hasProcessTime()) {
                    setProcessTime(other.getProcessTime());
                }
                if (other.hasPartitionTime()) {
                    setPartitionTime(other.getPartitionTime());
                }
                if (other.hasDataType()) {
                    setDataType(other.getDataType());
                }
                if (other.hasUrl()) {
                    setUrl(other.getUrl());
                }
                if (other.hasErrorCode()) {
                    setErrorCode(other.getErrorCode());
                }
                if (other.hasHttpStatus()) {
                    setHttpStatus(other.getHttpStatus());
                }
                if (other.hasCallerIp()) {
                    setCallerIp(other.getCallerIp());
                }
                if (other.hasLocalIp()) {
                    setLocalIp(other.getLocalIp());
                }
                if (other.hasString1()) {
                    setString1(other.getString1());
                }
                if (other.hasString2()) {
                    setString2(other.getString2());
                }
                if (other.hasString3()) {
                    setString3(other.getString3());
                }
                if (other.hasString4()) {
                    setString4(other.getString4());
                }
                if (other.hasString5()) {
                    setString5(other.getString5());
                }
                if (other.hasIsRedirectedUrl()) {
                    setIsRedirectedUrl(other.getIsRedirectedUrl());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            processTime_ = input.readUInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            partitionTime_ = input.readUInt32();
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();
                            com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType value = com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(3, rawValue);
                            } else {
                                bitField0_ |= 0x00000004;
                                dataType_ = value;
                            }
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            url_ = input.readBytes();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            errorCode_ = input.readUInt32();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            httpStatus_ = input.readUInt32();
                            break;
                        }
                        case 58: {
                            bitField0_ |= 0x00000040;
                            callerIp_ = input.readBytes();
                            break;
                        }
                        case 66: {
                            bitField0_ |= 0x00000080;
                            localIp_ = input.readBytes();
                            break;
                        }
                        case 74: {
                            bitField0_ |= 0x00000100;
                            string1_ = input.readBytes();
                            break;
                        }
                        case 82: {
                            bitField0_ |= 0x00000200;
                            string2_ = input.readBytes();
                            break;
                        }
                        case 90: {
                            bitField0_ |= 0x00000400;
                            string3_ = input.readBytes();
                            break;
                        }
                        case 98: {
                            bitField0_ |= 0x00000800;
                            string4_ = input.readBytes();
                            break;
                        }
                        case 106: {
                            bitField0_ |= 0x00001000;
                            string5_ = input.readBytes();
                            break;
                        }
                        case 112: {
                            bitField0_ |= 0x00002000;
                            isRedirectedUrl_ = input.readBool();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional uint32 process_time = 1;
            private int processTime_ ;
            public boolean hasProcessTime() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            public int getProcessTime() {
                return processTime_;
            }
            public Builder setProcessTime(int value) {
                bitField0_ |= 0x00000001;
                processTime_ = value;
                onChanged();
                return this;
            }
            public Builder clearProcessTime() {
                bitField0_ = (bitField0_ & ~0x00000001);
                processTime_ = 0;
                onChanged();
                return this;
            }

            // optional uint32 partition_time = 2;
            private int partitionTime_ ;
            public boolean hasPartitionTime() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            public int getPartitionTime() {
                return partitionTime_;
            }
            public Builder setPartitionTime(int value) {
                bitField0_ |= 0x00000002;
                partitionTime_ = value;
                onChanged();
                return this;
            }
            public Builder clearPartitionTime() {
                bitField0_ = (bitField0_ & ~0x00000002);
                partitionTime_ = 0;
                onChanged();
                return this;
            }

            // optional .com.tencent.attribution.flink.proto.gdt.HttpPingDataType data_type = 3;
            private com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType dataType_ = com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType.UNKNOWN;
            public boolean hasDataType() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            public com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType getDataType() {
                return dataType_;
            }
            public Builder setDataType(com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                dataType_ = value;
                onChanged();
                return this;
            }
            public Builder clearDataType() {
                bitField0_ = (bitField0_ & ~0x00000004);
                dataType_ = com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingDataType.UNKNOWN;
                onChanged();
                return this;
            }

            // optional string url = 4;
            private java.lang.Object url_ = "";
            public boolean hasUrl() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            public String getUrl() {
                java.lang.Object ref = url_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    url_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setUrl(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                url_ = value;
                onChanged();
                return this;
            }
            public Builder clearUrl() {
                bitField0_ = (bitField0_ & ~0x00000008);
                url_ = getDefaultInstance().getUrl();
                onChanged();
                return this;
            }
            void setUrl(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000008;
                url_ = value;
                onChanged();
            }

            // optional uint32 error_code = 5;
            private int errorCode_ ;
            public boolean hasErrorCode() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }
            public int getErrorCode() {
                return errorCode_;
            }
            public Builder setErrorCode(int value) {
                bitField0_ |= 0x00000010;
                errorCode_ = value;
                onChanged();
                return this;
            }
            public Builder clearErrorCode() {
                bitField0_ = (bitField0_ & ~0x00000010);
                errorCode_ = 0;
                onChanged();
                return this;
            }

            // optional uint32 http_status = 6;
            private int httpStatus_ ;
            public boolean hasHttpStatus() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }
            public int getHttpStatus() {
                return httpStatus_;
            }
            public Builder setHttpStatus(int value) {
                bitField0_ |= 0x00000020;
                httpStatus_ = value;
                onChanged();
                return this;
            }
            public Builder clearHttpStatus() {
                bitField0_ = (bitField0_ & ~0x00000020);
                httpStatus_ = 0;
                onChanged();
                return this;
            }

            // optional string caller_ip = 7;
            private java.lang.Object callerIp_ = "";
            public boolean hasCallerIp() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }
            public String getCallerIp() {
                java.lang.Object ref = callerIp_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    callerIp_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setCallerIp(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                callerIp_ = value;
                onChanged();
                return this;
            }
            public Builder clearCallerIp() {
                bitField0_ = (bitField0_ & ~0x00000040);
                callerIp_ = getDefaultInstance().getCallerIp();
                onChanged();
                return this;
            }
            void setCallerIp(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000040;
                callerIp_ = value;
                onChanged();
            }

            // optional string local_ip = 8;
            private java.lang.Object localIp_ = "";
            public boolean hasLocalIp() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }
            public String getLocalIp() {
                java.lang.Object ref = localIp_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    localIp_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setLocalIp(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                localIp_ = value;
                onChanged();
                return this;
            }
            public Builder clearLocalIp() {
                bitField0_ = (bitField0_ & ~0x00000080);
                localIp_ = getDefaultInstance().getLocalIp();
                onChanged();
                return this;
            }
            void setLocalIp(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000080;
                localIp_ = value;
                onChanged();
            }

            // optional string string1 = 9;
            private java.lang.Object string1_ = "";
            public boolean hasString1() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }
            public String getString1() {
                java.lang.Object ref = string1_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    string1_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setString1(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                string1_ = value;
                onChanged();
                return this;
            }
            public Builder clearString1() {
                bitField0_ = (bitField0_ & ~0x00000100);
                string1_ = getDefaultInstance().getString1();
                onChanged();
                return this;
            }
            void setString1(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000100;
                string1_ = value;
                onChanged();
            }

            // optional string string2 = 10;
            private java.lang.Object string2_ = "";
            public boolean hasString2() {
                return ((bitField0_ & 0x00000200) == 0x00000200);
            }
            public String getString2() {
                java.lang.Object ref = string2_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    string2_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setString2(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000200;
                string2_ = value;
                onChanged();
                return this;
            }
            public Builder clearString2() {
                bitField0_ = (bitField0_ & ~0x00000200);
                string2_ = getDefaultInstance().getString2();
                onChanged();
                return this;
            }
            void setString2(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000200;
                string2_ = value;
                onChanged();
            }

            // optional string string3 = 11;
            private java.lang.Object string3_ = "";
            public boolean hasString3() {
                return ((bitField0_ & 0x00000400) == 0x00000400);
            }
            public String getString3() {
                java.lang.Object ref = string3_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    string3_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setString3(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000400;
                string3_ = value;
                onChanged();
                return this;
            }
            public Builder clearString3() {
                bitField0_ = (bitField0_ & ~0x00000400);
                string3_ = getDefaultInstance().getString3();
                onChanged();
                return this;
            }
            void setString3(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000400;
                string3_ = value;
                onChanged();
            }

            // optional string string4 = 12;
            private java.lang.Object string4_ = "";
            public boolean hasString4() {
                return ((bitField0_ & 0x00000800) == 0x00000800);
            }
            public String getString4() {
                java.lang.Object ref = string4_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    string4_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setString4(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000800;
                string4_ = value;
                onChanged();
                return this;
            }
            public Builder clearString4() {
                bitField0_ = (bitField0_ & ~0x00000800);
                string4_ = getDefaultInstance().getString4();
                onChanged();
                return this;
            }
            void setString4(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000800;
                string4_ = value;
                onChanged();
            }

            // optional string string5 = 13;
            private java.lang.Object string5_ = "";
            public boolean hasString5() {
                return ((bitField0_ & 0x00001000) == 0x00001000);
            }
            public String getString5() {
                java.lang.Object ref = string5_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    string5_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setString5(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00001000;
                string5_ = value;
                onChanged();
                return this;
            }
            public Builder clearString5() {
                bitField0_ = (bitField0_ & ~0x00001000);
                string5_ = getDefaultInstance().getString5();
                onChanged();
                return this;
            }
            void setString5(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00001000;
                string5_ = value;
                onChanged();
            }

            // optional bool is_redirected_url = 14;
            private boolean isRedirectedUrl_ ;
            public boolean hasIsRedirectedUrl() {
                return ((bitField0_ & 0x00002000) == 0x00002000);
            }
            public boolean getIsRedirectedUrl() {
                return isRedirectedUrl_;
            }
            public Builder setIsRedirectedUrl(boolean value) {
                bitField0_ |= 0x00002000;
                isRedirectedUrl_ = value;
                onChanged();
                return this;
            }
            public Builder clearIsRedirectedUrl() {
                bitField0_ = (bitField0_ & ~0x00002000);
                isRedirectedUrl_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.tencent.attribution.flink.proto.gdt.HttpPingRecord)
        }

        static {
            defaultInstance = new HttpPingRecord(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.tencent.attribution.flink.proto.gdt.HttpPingRecord)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\017http_ping.proto\022\'com.tencent.attributi" +
                        "on.flink.proto.gdt\"\327\002\n\016HttpPingRecord\022\024\n" +
                        "\014process_time\030\001 \001(\r\022\026\n\016partition_time\030\002 " +
                        "\001(\r\022L\n\tdata_type\030\003 \001(\01629.com.tencent.att" +
                        "ribution.flink.proto.gdt.HttpPingDataTyp" +
                        "e\022\013\n\003url\030\004 \001(\t\022\022\n\nerror_code\030\005 \001(\r\022\023\n\013ht" +
                        "tp_status\030\006 \001(\r\022\021\n\tcaller_ip\030\007 \001(\t\022\020\n\010lo" +
                        "cal_ip\030\010 \001(\t\022\017\n\007string1\030\t \001(\t\022\017\n\007string2" +
                        "\030\n \001(\t\022\017\n\007string3\030\013 \001(\t\022\017\n\007string4\030\014 \001(\t" +
                        "\022\017\n\007string5\030\r \001(\t\022\031\n\021is_redirected_url\030\016",
                " \001(\010*\223\005\n\020HttpPingDataType\022\013\n\007UNKNOWN\020\000\022#" +
                        "\n\037GDT_EXPOSURE_THIRDPARTY_MONITOR\020\001\022\034\n\030G" +
                        "DT_EXPOSURE_DSP_MONITOR\020\002\022&\n\"WECHAT_EXPO" +
                        "SURE_THIRDPARTY_MONITOR\020\003\022\037\n\033WECHAT_EXPO" +
                        "SURE_DSP_MONITOR\020\004\022*\n&CLICK_MONITOR_FOR_" +
                        "MOBILEAPP_ACTIVITION\020\005\022\025\n\021CLICK_DSP_MONI" +
                        "TOR\020\006\022\034\n\030CLICK_THIRDPARTY_MONITOR\020\007\022\'\n#E" +
                        "XPOSURE_THIRDPARTY_MONITOR_FOR_ADX\020\010\022\027\n\023" +
                        "CLICK_DISPATCH_REDO\020\t\022\026\n\022CLICK_LANDING_P" +
                        "AGE\020\n\022\025\n\021CLICK_TRACKING_JD\020\013\022\025\n\021CLICK_TR",
                "ACKING_58\020\014\022\"\n\036CLICK_DSP_FOR_TRACE_COLLE" +
                        "CTION\020\r\022\025\n\021TRACE_DSP_MONITOR\020\016\022\033\n\027DISPAT" +
                        "CH_FOR_ADPLATFORM\020\017\022\024\n\020DISPATCH_FOR_DSP\020" +
                        "\020\022!\n\034CLICK_FOR_THIRDPARTY_MONITOR\020\201\002\022#\n\036" +
                        "CLICK_FOR_MOBILEAPP_ACTIVITION\020\202\002\022+\n&EXP" +
                        "OSURE_FOR_WECHAT_THIRDPARTY_MONITOR\020\201\004\022\032" +
                        "\n\025WECHAT_TRACE_DISPATCH\020\202\004B\032B\022GDTHttpPin" +
                        "gService\200\001\001\210\001\001"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_tencent_attribution_flink_proto_gdt_HttpPingRecord_descriptor,
                                new java.lang.String[] { "ProcessTime", "PartitionTime", "DataType", "Url", "ErrorCode", "HttpStatus", "CallerIp", "LocalIp", "String1", "String2", "String3", "String4", "String5", "IsRedirectedUrl", },
                                com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord.class,
                                com.tencent.attribution.flink.proto.gdt.GDTHttpPingService.HttpPingRecord.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
